# Generated by Django 4.0.2 on 2022-06-01 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_darjah'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='darjah',
            field=models.CharField(blank=True, choices=[('1', 'Darjah 1'), ('2', 'Darjah 2')], max_length=100, null=True),
        ),
    ]
