# Generated by Django 4.0.2 on 2022-05-29 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='kelas',
            field=models.CharField(blank=True, choices=[(1, 'Intan'), (2, 'Nilam')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(blank=True, choices=[(1, 'Admin'), (2, 'Manager'), (3, 'Employee')], max_length=100, null=True),
        ),
    ]
