# Generated by Django 4.0.2 on 2022-06-01 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_alter_userprofile_kelas_alter_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='darjah',
            field=models.CharField(blank=True, choices=[(1, 'Darjah 1'), (2, 'Darjah 2')], max_length=100, null=True),
        ),
    ]
