# Generated by Django 4.0.2 on 2022-06-01 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_alter_userprofile_darjah'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='darjah',
            field=models.CharField(blank=True, choices=[('1', 'Darjah 1'), ('2', 'Darjah 2')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='kelas',
            field=models.CharField(blank=True, choices=[('Intan', 'Intan'), ('Nilam', 'Nilam')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(blank=True, choices=[('Teacher', 'Teacher'), ('Student', 'Student')], max_length=100, null=True),
        ),
    ]
